export const authActionTypes = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOG_OUT: 'LOG_OUT',
  LOADING_LOGIN: 'LOADING_LOGIN',
  RESET_MESSAGE_ERR: 'RESET_MESSAGE_ERR',
  LOGOUT: 'LOGOUT',
  SAVE_DEVICE_TOKEN:'SAVE_DEVICE_TOKEN',
  USER_LOGIN:'USER_LOGIN'
};
export const SettingActionTypes ={
  CHANGE_DATE:'CHANGE_DATE',
  SET_LOADING:'SET_LOADING',
  CHANGE_THEME:'CHANGE_THEME'
}

export const homeActionTypes={
  GET_BANNER_HOME:'GET_BANNER_HOME',
  COUNT_ALL_DATA: 'COUNT_ALL_DATA',
  COUNT_DATA: 'COUNT_DATA',
}

export const newsActionTypes={
  GET_ALL_NEWS:"GET_ALL_NEWS",
  INCREMENT_NUMBER:"INCREMENT_NUMBER",

}
export const warnningActionTypes={
  QUERY_WARNNING:"QUERY_WARNNING"
}
export const reportActionTypes={
  QUERY_VIOLATE_POLICY:"QUERY_VIOLATE_POLICY",
  QUERY_ATTACK_WEB:"QUERY_ATTACK_WEB",
  QUERY_MACHINE_MALWARE:"QUERY_MACHINE_MALWARE"
}
export const notifyActionTypes={
   QUERY_ALL_NOTIFY :'QUERY_ALL_NOTIFY',
   RECEIVED_NOTIFY : 'RECEIVED_NOTIFY',
   READ_NOTIFY : 'READ_NOTIFY',
}
export const courseActionTypes = {
   QUERY_ALL_COURSE :'QUERY_ALL_COURSE',
   QUERY_ALL_LESSON :'QUERY_ALL_LESSON'
}
export const instructionActionTypes = {
  QUERY_ALL_INSTRUCTION :'QUERY_ALL_INSTRUCTION',
}
export const contactActionTypes = {
  QUERY_ALL_CONTACT :'QUERY_ALL_CONTACT',
}
export const FAQActionTypes = {
  QUERY_ALL_FAQ :'QUERY_ALL_FAQ',
}

